Back-end/building_rails_apps/rails-todo/config/routes.rb
Rails.application.routes.draw do
  resources :todos
end

Back-end/building_rails_apps/rails-todo/app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :text, presence: :true
end

Back-end/building_rails_apps/rails-todo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Back-end/building_rails_apps/rails-todo/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to @todo
    else
      render :new
    end
  end

  def show
    @todo = Todo.find(params[:id])
  end

  private

  def todo_params
    params.require(:todo).permit(:text)
  end
end

Back-end/building_rails_apps/rails-todo/app/helpers/application_helper.rb
module ApplicationHelper
end

Back-end/building_rails_apps/rails-todo/app/helpers/todos_helper.rb
module TodosHelper
end

Back-end/building_rails_apps/rails-todo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTodo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Back-end/building_rails_apps/rails-todo/app/views/todos/index.html.erb
<%= link_to 'New todo', todos_new_path %>

<ul class='list'>
<% @todos.each do |todo| %>
  <li class='todo'>
    <%= todo.text %>
  </li>
<% end %>
</ul>

Back-end/building_rails_apps/rails-todo/app/views/todos/new.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Back-end/building_rails_apps/rails-todo/app/views/todos/show.html.erb
<h1>Life moves pretty fast</h1>
<h2>If you don't stop and look around once in a while...</h2>
<h3>You might miss it</h3>

<p>
  <%= @todo.text %>
</p>