Full-stack/full_example/config/routes.rb
Rails.application.routes.draw do
  get 'todos/index'

  get 'todos/show'

  get 'todos/new'

  get 'todos/edit'

  get 'todos/create'

  get 'todos/destroy'

  get 'todos/update'

  resources :users, only: [ :index, :show, :new, :create ]
  resources :todos
  get "/login" => "users#login", as: "login"
  post "/sessions" => "sessions#login"
  delete "/sessions" => "sessions#logout", as: "logout" # logout_path is now defined
  root "users#new"
end

# post "/login" => "sessions#login"
# delete "/logout" => "sessions#logout", as: "logout"

Full-stack/full_example/app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
end

Full-stack/full_example/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password, :on => :create
  # validates :password, presence: true, on: :create
  has_many :todos

end

Full-stack/full_example/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authorize
    redirect_to root_path unless current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

Full-stack/full_example/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
    user = User.find_by({username: params[:username]})
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      session[:user_id] = nil
      redirect_to root_path
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end
end

Full-stack/full_example/app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_filter :authorize

  def index
    @todos = current_user.todos
    respond_to do |format|
      format.html
      format.json { render :json => { todos: @todos }}
    end
  end

  def show
    @todo = current_user.todos.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => { todo: @todo }}
    end
  end

  def new
    # @todo = current_user.todos.new
    @todo = Todo.new
  end

  def edit
    @todo = current_user.todos.find(params[:id])
  end

  def create
    # todo = Todo.create(todo_params)
    # current_user.todos << todo
    todo = current_user.todos.create(todo_params)
    respond_to do |format|
      format.html { redirect_to todo_path(todo) }
      format.json { render :json => { todo: todo }}
    end
  end

  def destroy
    todo = current_user.todos.delete(params[:id])
    respond_to do |format|
      format.html { redirect_to todos_path }
      format.json { render :json => { todo: todo }}
    end
  end

  def update
    todo = current_user.todos.find(params[:id])
    todo.update(todo_params)
    respond_to do |format|
      format.html { redirect_to todo_path(todo) }
      format.json { render :json => { todo: todo }}
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:text)
  end

end

Full-stack/full_example/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authorize, except: [:new, :create, :login]

  def index
    @users = User.all
  end

  def show
    @user = current_user
  end

  def new
    # cuz we using a form helper
    @user = User.new
  end

  def create
    user = User.create(user_params)
    redirect_to user_path(user)
    # redirect_to user     (also works)
  end

  def edit
    @user = User.new
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(user)
  end

  def destroy
    user = User.find(params[:id])
    user.destroy!
    redirect_to users_path
  end

  def login

  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

Full-stack/full_example/app/helpers/application_helper.rb
module ApplicationHelper
end

Full-stack/full_example/app/helpers/todos_helper.rb
module TodosHelper
end

Full-stack/full_example/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LemurTodos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script id="todo-template" type="text/template" >
    <li class="todo">
      <div>
         <%%= todo.text %>
         <em><%%= todo.createdAt %></em>
      </div>
    </li>
  </script>
</head>
<body>
  <nav>
    <%= render partial: current_user ? "/shared/user_nav" : "/shared/non_user_nav" %>
  </nav>
<%= yield %>

</body>
</html>

Full-stack/full_example/app/views/shared/_non_user_nav.html.erb
<div>
  <%= button_to  "Login", login_path, method: :get %>
  <%= button_to "Signup", new_user_path, method: :get %>
</div>

Full-stack/full_example/app/views/shared/_user_nav.html.erb
<div>
  <%= button_to "logout", logout_path, method: :delete %>
</div>

Full-stack/full_example/app/views/todos/_form.html.erb
<%= form_for @todo do |f| %>
  <p>
    <%= f.label :text %>
    <%= f.text_field :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

Full-stack/full_example/app/views/todos/edit.html.erb
<h1>Todos#edit</h1>
<p>Find me in app/views/todos/edit.html.erb</p>
<%= render partial: 'form' %>

Full-stack/full_example/app/views/todos/index.html.erb
<h1>Todos#index</h1>
<p>Find me in app/views/todos/index.html.erb</p>

Full-stack/full_example/app/views/todos/new.html.erb
<h1>Todos#new</h1>
<p>Find me in app/views/todos/new.html.erb</p>
<%= render partial:'form' %>

Full-stack/full_example/app/views/todos/show.html.erb
<h1>THIS IS A TODO</h1>
<h2>Its text: <%= @todo.text %></h2>
<h2>Its user: <%= @todo.user.username %></h2>

Full-stack/full_example/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <%= f.submit :submit %>
<% end %>

Full-stack/full_example/app/views/users/edit.html.erb
<h1>Edit a User</h1>
<%= render partial: "form" %>

Full-stack/full_example/app/views/users/index.html.erb
<ul>
  <% @users.each do |username| %>
    <li><%= username %></li>
  <% end %>
</ul>

Full-stack/full_example/app/views/users/login.html.erb
<h3>Welcome back...login to proceed</h3>

<form action="/sessions" method="post">
  <%= token_tag %>
  <input type="text" name="username">
  <input type="password" name="password">
  <input type="submit" value="Log In">
</form>

Full-stack/full_example/app/views/users/new.html.erb
<h1>Create New User</h1>
<%= render partial: "form" %>

Full-stack/full_example/app/views/users/show.html.erb
<h1><%= @user.username %> will eventually have todos</h1>
<form id="new-todo" action="">
  <input type="text" name="todo[text]">
  <input type="submit">
</form>
<ul class="todos"></ul>
<script>
  var todoList = new TodoList({model: Todo});
  $(document).ready(function(){
    var listView = new TodoListView({
      collection: todoList,
      $el: $(".todos")
    });
    $("#new-todo").on("submit", function(e){
      e.preventDefault();
      var $textField = $(this).find("input[name='todo[text]']");
      var todo = new Todo({text: $textField.val()});
      todoList.create(todo);
    })
    todoList.fetch();
  });
</script>