Back-end/building_rails_apps/full_rails_app/config/routes.rb
Rails.application.routes.draw do
  # miscellaneous
  get "/"                     => 'welcome#index', as: 'root'
  get "/about"                => 'welcome#about', as: 'about'

  # artists, songs
  resources :artists, :songs

  # playlists
  get  "playlists"                    => 'playlists#index', as: 'playlists'
  get  "playlists/new"                => 'playlists#new', as: 'new_playlist'
  post "playlists"                    => 'playlists#create'
  get  "playlists/:id"                => 'playlists#show', as: 'playlist'
  post "playlists/:id/add_song"       => 'playlists#add_song', as: 'add_song_to_playlist'
  post "playlists/:id/remove_song"    => 'playlists#remove_song', as: 'remove_song_from_playlist'
end

Back-end/building_rails_apps/full_rails_app/app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs

  validates :name, :nationality, presence: true
  validates :name, uniqueness: true
  validates :name, length: { maximum: 50 }
end

Back-end/building_rails_apps/full_rails_app/app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_and_belongs_to_many :songs

  validates :name, presence: true
  validates :name, uniqueness: true
end

Back-end/building_rails_apps/full_rails_app/app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  has_and_belongs_to_many :playlists

  validates :title, :artist, :price, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

Back-end/building_rails_apps/full_rails_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Back-end/building_rails_apps/full_rails_app/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to(artist_path(@artist))
    else
      render(:new)
    end
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update(artist_params)
      redirect_to(artist_path(@artist))
    else
      render(:edit)
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to(artists_path)
  end

  private
  def artist_params
    params.require(:artist).permit(:name, :photo_url, :nationality)
  end

end

Back-end/building_rails_apps/full_rails_app/app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
    @playlists = Playlist.all
  end

  def new
    @playlist = Playlist.new
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def create
    @playlist = Playlist.new(playlist_params)
    if @playlist.save
      redirect_to(playlist_path(@playlist))
    else
      render(:new)
    end
  end

  def add_song
    @playlist = Playlist.find(params[:id])
    @playlist.songs << Song.find(params[:song_id])
    redirect_to(playlist_path(@playlist))
  end

  def remove_song
    @playlist = Playlist.find(params[:id])
    @playlist.songs.delete(Song.find(params[:song_id]))
    redirect_to(playlist_path(@playlist))
  end

  private
  def playlist_params
    params.require(:playlist).permit(:name)
  end
end

Back-end/building_rails_apps/full_rails_app/app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      redirect_to(song_path(@song))
    else
      render(:new)
    end
  end

  def show
    @song = Song.find(params[:id])
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      redirect_to(song_path(@song))
    else
      render(:edit)
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to(songs_path)
  end

  private
  def song_params
    params.require(:song).permit(:title, :album, :preview_url, :artist_id, :price)
  end

end

Back-end/building_rails_apps/full_rails_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

Back-end/building_rails_apps/full_rails_app/app/helpers/application_helper.rb
module ApplicationHelper
end

Back-end/building_rails_apps/full_rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tunr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>Tun.r</h1>
  <%= link_to('Home', root_path) %>
  <%= link_to('Songs', songs_path) %>
  <%= link_to('Artists', artists_path) %>
  <%= link_to('Playlists', playlists_path) %>
  <%= link_to('About', about_path) %>
  
  <%= yield %>
</body>

</html>

Back-end/building_rails_apps/full_rails_app/app/views/playlists/index.html.erb
<h2>Playlists</h2>

<%= link_to('Add Playlist', new_playlist_path) %>

<ul>
  <% @playlists.each do |playlist| %>
    <li>
      <%= link_to("#{playlist.name} (#{playlist.songs.count} songs)" , playlist_path(playlist)) %>
    </li>
  <% end %>
</ul>

Back-end/building_rails_apps/full_rails_app/app/views/playlists/new.html.erb
<h2>New Playlist</h2>

<h3>Errors</h3>
<ul>
<% @playlist.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>
</ul>

<%= form_for @playlist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

Back-end/building_rails_apps/full_rails_app/app/views/playlists/show.html.erb
<h2><%= @playlist.name %></h2>

<ul>
  <% @playlist.songs.each do |song| %>
    <li>
      <%= link_to("#{song.title} - #{song.artist.name}", song_path(song)) %>
    </li>
  <% end %>
</ul>

<h3>Add Song by ID</h3>
<form action="<%= add_song_to_playlist_path(@playlist) %>" method="post">
  <label  for="song_id">Song ID:</label>
  <input name="song_id">

  <input type="submit">
</form>

<h3>Remove Song by ID</h3>
<form action="<%= remove_song_from_playlist_path(@playlist) %>" method="post">
  <label  for="song_id">Artist ID:</label>
  <input name="song_id">

  <input type="submit">
</form>

<h3>Add Song by Title</h3>
<form action="<%= add_song_to_playlist_path(@playlist) %>" method="post">
  <select name="song_id">
    <% Song.all.each do |song| %>
      <option value="<%= song.id%>">
        <%= song.artist.name + " - " + song.title %>
      </option>
    <% end %>
  </select>
  <input type="submit">
</form>

<h3>Remove Song by Title</h3>
<form action="<%= remove_song_from_playlist_path(@playlist) %>" method="post">
  <select name="song_id">
    <% Song.all.each do |song| %>
      <option value="<%= song.id%>">
        <%= song.artist.name + " - " + song.title %>
      </option>
    <% end %>
  </select>
  <input type="submit">
</form>

Back-end/building_rails_apps/full_rails_app/app/views/songs/edit.html.erb
<h2>Edit Song</h2>

<h3>Errors</h3>
<ul>
<% @song.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>
</ul>

<%= form_for(@song) do |f| %>
  <%= f.label(:title) %>
  <%= f.text_field(:title) %>

  <%= f.label(:album) %>
  <%= f.text_field(:album) %>

  <%= f.label(:preview_url) %>
  <%= f.text_field(:preview_url) %>

  <%= f.label(:artist) %>
  <%= f.collection_select(:artist_id, Artist.all, :id, :name) %>

  <%= f.label(:price) %>
  <%= f.text_field(:price) %>

  <%= f.submit %>
<% end %>

<%= link_to('Back', song_path(@song)) %>
<%= link_to('Delete', song_path(@song), method: :delete) %>

Back-end/building_rails_apps/full_rails_app/app/views/songs/index.html.erb
<h2>Songs</h2>

<%= link_to('Add Song', new_song_path) %>

<ul>
  <% @songs.each do |song| %>
    <li>
      <%= link_to(song.title, song_path(song)) %>
    </li>
  <% end %>
</ul>

Back-end/building_rails_apps/full_rails_app/app/views/songs/new.html.erb
<h2>New Song</h2>

<h3>Errors</h3>
<ul>
<% @song.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>
</ul>

<%= form_for(@song) do |f| %>
  <%= f.label(:title) %>
  <%= f.text_field(:title) %>

  <%= f.label(:album) %>
  <%= f.text_field(:album) %>

  <%= f.label(:preview_url) %>
  <%= f.text_field(:preview_url) %>

  <%= f.label(:artist) %>
  <%= f.collection_select(:artist_id, Artist.all, :id, :name) %>

  <%= f.label(:price) %>
  <%= f.text_field(:price) %>

  <%= f.submit %>
<% end %>

<%= link_to('Back to Songs', songs_path) %>

Back-end/building_rails_apps/full_rails_app/app/views/songs/show.html.erb
<h2><%= @song.title %></h2>
<h3>By: <%= @song.artist.name %></h3>

Album: <%= @song.album %></br>
Preview_url: <%= @song.preview_url %></br>
Price: <%= @song.price %></br>

<%= link_to('Edit', edit_song_path(@song)) %> |
<%= link_to('Back to Songs', songs_path) %> |
<%= link_to('Delete', song_path(@song), method: :delete) %>

Back-end/building_rails_apps/full_rails_app/app/views/welcome/about.html.erb
<p>
  Tun.r is a HAMco product. Have fun!
</p>

Back-end/building_rails_apps/full_rails_app/app/views/welcome/index.html.erb
<p>
  Welcome to Tun.r.
</p>